# Site variables #

name: Escola de Musica XóDó
url: www.escolademusicaxodo.com

ga_analytics: # Add Google Analytics tracking code

# Assets #

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn

# plugins #

plugins:
  - jekyll-assets
  - jekyll-sitemap

permalink: pretty

liquid:
  error_mode: strict

strict_front_matter: true

# Site #

exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - node_modules
